"""
Plagiarism Service - Handles plagiarism detection functionality for the Plagiarism tab
"""

import re
import json
from typing import Optional, List, Dict, Any
from fastapi import HTTPException, APIRouter
from pydantic import BaseModel
from utils import get_ai_client, extract_paper_content

# Create router for plagiarism endpoints
router = APIRouter(prefix="/api", tags=["plagiarism"])


class PlagiarismCheckRequest(BaseModel):
    file_ids: Optional[List[str]] = None
    paper_url: Optional[str] = None
    paper_name: Optional[str] = None


async def check_string_matching(text: str) -> Dict[str, Any]:
    """Check for copy-paste plagiarism using string matching"""
    # Simple heuristic: check for common phrases that might indicate copying
    # In a real implementation, this would compare against a database of papers
    suspicious_phrases = [
        "as shown in", "it is well known that", "previous work has shown",
        "we propose a novel", "the main contribution", "experimental results show"
    ]
    
    text_lower = text.lower()
    matches = []
    for phrase in suspicious_phrases:
        if phrase in text_lower:
            matches.append(phrase)
    
    # Check for very long identical sentences (potential copy-paste)
    sentences = re.split(r'[.!?]+', text)
    long_sentences = [s.strip() for s in sentences if len(s.strip()) > 100]
    
    detected = len(matches) > 5 or len(long_sentences) > 10
    
    return {
        "detected": detected,
        "description": "Detects copy-paste from the web or other papers",
        "difficulty": "Easy (just rewrite it)",
        "details": f"Found {len(matches)} common phrases. {'High similarity detected.' if detected else 'No obvious copy-paste patterns found.'}"
    }


async def check_semantic_analysis(text: str, model: str = "grok-4-fast") -> Dict[str, Any]:
    """Check for heavy paraphrasing using semantic analysis"""
    try:
        ai_client = get_ai_client()
        
        prompt = f"""Analyze the following text for signs of heavy paraphrasing or unoriginal content. 
Look for:
1. Ideas that are presented without proper attribution
2. Concepts that appear to be heavily paraphrased from other sources
3. Lack of original analysis or synthesis

Text to analyze:
{text[:3000]}

Respond with JSON:
{{
    "is_paraphrased": true/false,
    "confidence": 0.0-1.0,
    "explanation": "brief explanation"
}}"""

        response = ai_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert at detecting paraphrased or unoriginal academic content. Always respond with valid JSON only."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,
            max_tokens=300
        )
        
        result_text = response.choices[0].message.content.strip()
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
            result_text = result_text.strip()
        
        try:
            result = json.loads(result_text)
            detected = result.get("is_paraphrased", False) and result.get("confidence", 0) > 0.6
            return {
                "detected": detected,
                "description": "Detects heavy paraphrasing of ideas",
                "difficulty": "Hard (requires original logic)",
                "details": result.get("explanation", "Semantic analysis completed.")
            }
        except:
            return {
                "detected": False,
                "description": "Detects heavy paraphrasing of ideas",
                "difficulty": "Hard (requires original logic)",
                "details": "Analysis completed."
            }
    except Exception as e:
        return {
            "detected": False,
            "description": "Detects heavy paraphrasing of ideas",
            "difficulty": "Hard (requires original logic)",
            "details": f"Error in analysis: {str(e)}"
        }


async def check_ai_detection(text: str, model: str = "grok-4-fast") -> Dict[str, Any]:
    """Check if text was written by LLMs"""
    try:
        ai_client = get_ai_client()
        
        prompt = f"""Analyze if the following text appears to be generated by an AI/LLM. 
Look for:
1. Overly formal or generic language patterns
2. Lack of personal voice or unique style
3. Repetitive sentence structures
4. Unusual word choices typical of LLMs

Text to analyze:
{text[:3000]}

Respond with JSON:
{{
    "is_ai_generated": true/false,
    "confidence": 0.0-1.0,
    "explanation": "brief explanation"
}}"""

        response = ai_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert at detecting AI-generated text. Always respond with valid JSON only."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,
            max_tokens=300
        )
        
        result_text = response.choices[0].message.content.strip()
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
            result_text = result_text.strip()
        
        try:
            result = json.loads(result_text)
            detected = result.get("is_ai_generated", False) and result.get("confidence", 0) > 0.5
            return {
                "detected": detected,
                "description": "Detects text written by LLMs",
                "difficulty": "Medium (can be 'humanized')",
                "details": result.get("explanation", "AI detection analysis completed.")
            }
        except:
            return {
                "detected": False,
                "description": "Detects text written by LLMs",
                "difficulty": "Medium (can be 'humanized')",
                "details": "Analysis completed."
            }
    except Exception as e:
        return {
            "detected": False,
            "description": "Detects text written by LLMs",
            "difficulty": "Medium (can be 'humanized')",
            "details": f"Error in analysis: {str(e)}"
        }


async def check_stylometry(text: str) -> Dict[str, Any]:
    """Check for sudden changes in writing style (stylometry)"""
    # Analyze writing style consistency
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 10]
    
    if len(sentences) < 5:
        return {
            "detected": False,
            "description": "Detects sudden changes in your 'voice'",
            "difficulty": "Very Hard (mimicking style is difficult)",
            "details": "Insufficient text for stylometric analysis."
        }
    
    # Calculate average sentence length
    avg_lengths = [len(s.split()) for s in sentences]
    avg_len = sum(avg_lengths) / len(avg_lengths) if avg_lengths else 0
    
    # Check for variance in sentence length (sudden changes)
    if len(avg_lengths) > 1:
        variance = sum((x - avg_len) ** 2 for x in avg_lengths) / len(avg_lengths)
        std_dev = variance ** 0.5
        
        # High variance might indicate style changes
        detected = std_dev > avg_len * 0.8
    
        # Check for punctuation patterns
        punctuation_patterns = {}
        for sentence in sentences[:20]:  # Sample first 20 sentences
            punct_count = len(re.findall(r'[,;:—]', sentence))
            punctuation_patterns[punct_count] = punctuation_patterns.get(punct_count, 0) + 1
        
        # If punctuation patterns vary significantly, might indicate style change
        if len(punctuation_patterns) > 3:
            detected = True
    else:
        detected = False
    
    return {
        "detected": detected,
        "description": "Detects sudden changes in your 'voice'",
        "difficulty": "Very Hard (mimicking style is difficult)",
        "details": f"Analyzed {len(sentences)} sentences. {'Style inconsistencies detected.' if detected else 'Writing style appears consistent.'}"
    }


@router.post("/plagiarism-check")
async def plagiarism_check(request: PlagiarismCheckRequest):
    """Plagiarism checker endpoint using AI-based methods.
    
    This endpoint is designed for the Plagiarism tab where the intention is clear:
    - Paper content is provided via file upload, URL, or paper name
    - No query verification or web search needed
    - Directly extracts content and performs plagiarism analysis
    """
    try:
        # Extract paper content using the helper function
        paper_text, paper_metadata = await extract_paper_content(
            file_ids=request.file_ids,
            paper_url=request.paper_url,
            paper_name=request.paper_name,
            use_openreview=True  # Always use OpenReview for plagiarism check if available
        )
        
        if not paper_text or len(paper_text.strip()) < 100:
            raise HTTPException(
                status_code=400,
                detail="Could not extract sufficient text from the provided input. Please ensure the file, URL, or paper name is valid."
            )
        
        # Run all plagiarism detection methods
        methods = {}
        
        # String Matching
        methods["string_matching"] = await check_string_matching(paper_text)
        
        # Semantic Analysis
        methods["semantic_analysis"] = await check_semantic_analysis(paper_text)
        
        # AI Detection
        methods["ai_detection"] = await check_ai_detection(paper_text)
        
        # Stylometry
        methods["stylometry"] = await check_stylometry(paper_text)
        
        # Generate overall analysis using LLM
        ai_client = get_ai_client()
        analysis_prompt = f"""Based on the following plagiarism detection results, provide a comprehensive analysis:

String Matching: {methods["string_matching"]["detected"]} - {methods["string_matching"]["details"]}
Semantic Analysis: {methods["semantic_analysis"]["detected"]} - {methods["semantic_analysis"]["details"]}
AI Detection: {methods["ai_detection"]["detected"]} - {methods["ai_detection"]["details"]}
Stylometry: {methods["stylometry"]["detected"]} - {methods["stylometry"]["details"]}

Provide a summary analysis of the plagiarism check results, highlighting any concerns and recommendations."""

        try:
            analysis_response = ai_client.chat.completions.create(
                model="grok-4-fast",
                messages=[
                    {"role": "system", "content": "You are an expert academic integrity advisor. Provide clear, professional analysis."},
                    {"role": "user", "content": analysis_prompt}
                ],
                temperature=0.5,
                max_tokens=500
            )
            analysis = analysis_response.choices[0].message.content
        except:
            analysis = "Plagiarism check completed. Review the detailed results above."
        
        response_data = {
            "methods": methods,
            "analysis": analysis,
            "text_length": len(paper_text),
            "paper_metadata": paper_metadata
        }
        
        # Add PDF links if available
        if paper_metadata:
            pdf_links = []
            if paper_metadata.get('paper_id'):
                # OpenReview paper - construct URL
                pdf_links.append({
                    "title": paper_metadata.get('title', 'Paper') or 'Paper',
                    "url": f"https://openreview.net/pdf?id={paper_metadata['paper_id']}",
                    "review_url": f"https://openreview.net/forum?id={paper_metadata['paper_id']}",
                    "source": "openreview"
                })
            elif paper_metadata.get('url'):
                # Web search paper
                pdf_links.append({
                    "title": paper_metadata.get('title', 'Paper') or 'Paper',
                    "url": paper_metadata['url'],
                    "source": "web_search"
                })
            if pdf_links:
                response_data["pdf_links"] = pdf_links
        
        return response_data
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error in plagiarism check: {str(e)}")
